[profile.default]
solc-version = "0.8.18"
src = "src"
out = "artifacts"
libs = ["lib"]
ffi = true
fs_permissions = [{ access = "read-write", path = "./"}]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
base_goerli = "https://goerli.base.org"

[etherscan]
base_goerli = { key = "PLACEHOLDER", url = "https://api-goerli.basescan.org/api" }